---
  TRADE_OPTIONS:
    QUANTITY: 50
    PAIRING: USDT
    # How often to check for posts in seconds
    RUN_EVERY: 600
    TEST: True
    SL: 1
    TP: 1
    ENABLE_TSL: False
    TSL: 1
    TTP: 1
    CONSIDER_DELAY: False
    PERCENTAGE: 0.2
    #take in consideration the delay to place the order
    #since the ping includes also the time it takes binance to process the order we take a little percent of that time
    #if running close to tokyo better  leave it false,
